baseurl: /jekyll/
sass:
    sass_dir: _sass
    style: compressed


#gems: [jekyll-paginate]

#分页模块
paginate: 6

#指定引用哪个插件
plugins: [jekyll-paginate]

highlighter: rouge

lianjie: [{"name":"李泽龙","url":"https://www.lizelong.com/"}]
#遍历的对象要从site改为paginator